module.exports.articles = [
  {
  "id": 1,
  "home_image": "http://usjus.org/wp-content/uploads/2020/01/WeChat-Image_20200110170628-768x1855.jpg",
  "home_title": "USJ The 4th USJ Education Annual Meeting and 2020 New Year Reception Topic： AI and Community Economy",
  "public_time": "January 10, 2020",
  "author": "USJ",
  "news_content": "USJ",
  "news_content1": "The 4th USJ Education Annual Meeting and 2020 New Year Reception Topic： AI and Community Economy",
  "news_content2": "Please contact Tiffany Tian to register",
  "news_content3": "Phone: 630-401-6921",
  "news_content4": "Email: tiffanytian@usjus.org",
  "news_content5": "Date: 01-25-2020 2:00 – 8:00pm"
},
{
  "id": 2,
  "home_image": "http://usjus.org/wp-content/uploads/2019/11/WeChat-Image_20191120133108.jpg",
  "home_title": "USJ Non-Profit Activities: 2020 H1B Bootcamp",
  "public_time": "November 21, 2019",
  "author": "USJ",
  "news_content": "USJ Non-Profit Activities: 2020 H1B Bootcamp",
  "news_content1": "Expert Opinion | Case Study | Training | Ice Breaking",
  "news_content2": "Event Background",
  "news_content3": "2021 Fiscal Year H1B Lottery Coming, USJ are Here to Help",
  "news_content4": "H1B lottery in 2020 is about to start. As the most important work visa category in the United States, H1B is a visa issued to US companies to hire foreign professionals. According to the official data of the US Immigration Service, the number of H1B visa applicants in the 2020 fiscal year is 201,011. Incomplete statistics show that the chance of being selected is roughly 50%. Although the selection rate has increased compared to previous years, the denial rate of H1B petition after the selection has reached 32%. You should be prepared for the situation that both of the lot probability and the denial rate are increasing.",
  "news_content5": "Jointly with Immigration Experts in the Bay Area to Serve International Students",
  "news_content6": "Sometimes, students get the sponsorship to participate in the lottery, but eventually miss the H1B visa due to some filing errors. That is the situation we are trying to avoid you from. USJ collaborated with the SAC Attorneys firm, delivers the “2020 H1B Bootcamp” to you. This camp is to help you become more familiar with CPT/ OPT/ H1B policies, and finally step into a new stage of life. In the process of preparing the application, any tiny oversight or mistake could lead to severe consequences, due to the complexity and requirements of the U.S. Citizenship and Immigration Service(USCIS). The bad consequences ranges from refiling the materials to losing the legal status of staying in the United States.",
  "news_content7": "2020 H1B Bootcamp Integrates Onsite and Online Delivery",
  "news_content8": "This Bootcamp willd the online training will be held o be conducted onsite and online. The onsite training will be held at USJ, ann the ZOOM platform.",
  "news_content9": "Main Features",
  "news_content10": "1. Guiding by legal experts in Silicon Valley!",
  "news_content11": "Senior attorney James Cai and his team are here to help you solve the H1B problems. You can discuss the most crucial factors that affect the RFE rate in the previous years with our experts!",
  "news_content12": "2. Previous case sharing!",
  "news_content13": "Even Homer sometimes nods. H1B application submission process is complicated and cumbersome. Some students end up in failure on the materials filling, submission, inspection, and so on. In this Bootcamp, USJ and SAC law firm apply solid cases to explain the factors behind the filing procedures, and thus improve students’ applications.",
  "news_content14": "3. Immersive training",
  "news_content15": "Unity of knowledge and action ends at goodness. The purpose of this Bootcamp is not only to spread theoretical knowledge, but more importantly, to prevent you from making mistakes or wasting your time on unnecessary steps. With use of different application cases, USJ integrates several up-to-date training subjects to reduce the difficulties during the application. At the same time, students will be able to meet like-minded peers and overcome difficulties together.",
  "news_content16": "Activity module",
  "news_content17": "Expert Theory Lecture – 3 Sessions",
  "news_content18": "Practical case sharing – 3 CASE seminars",
  "news_content19": "Immersive training – 2 extended training",
  "news_content20": "Immigration Lawyer Team",
  "home_image1": "http://usjus.org/wp-content/uploads/2019/11/WeChat-Image_20191118181738.jpg",
  "news_content21": "1. James Cai",
  "news_content22": "Jingming Cai, J.D.,founded SAC Attorneys LLP after serving as in-house legal counsel for Yahoo! Inc. His practice focuses on corporate law, intellectual property, immigration, and real-estate planning.",
  "news_content23": "Before founding SAC Attorneys, Mr. Cai served as in-house counsel for Yahoo! Inc. He also practiced law with Morrison & Foerster, LLP and Gray Cary Ware & Freidenrich, LLP (now known as DLA Piper Rudnick Gray Cary), two of the largest law firms in California. Mr. Cai holds a Juris Doctor, Magna Cum Laude, from Temple University School of Law in Philadelphia, graduating in the top 5% of his class.",
  "news_content24": "Mr. Cai is admitted to practice in California, United States District Court for the Northern District of California, United States Court of Appeals for the Ninth Circuit and before the United States Patent and Trademark Office.",
  "home_image2": "http://usjus.org/wp-content/uploads/2019/11/WeChat-Image_20191118181457.jpg",
  "news_content25": "2. Woody Wu",
  "news_content26": "Woody Wu is an attorney who has multi-industries background. He has worked at Bank of America as a senior securities analyst and several other multinational corporations before joining SAC Attorneys LLP. With rich working experience in both China and the US, extensive experience in corporate operations and business negotiations, Mr. Wu specializes in helping clients to understand cultural and legal differences between China and the United States. In the summer of 2016, Mr. Wu gave a series of lectures on investing and immigrating to the US to entrepreneurs and high net worth individuals in several cities of China.",
  "news_content27": "Mr. Wu’s main practice areas are corporate, immigration, and civil litigation. Mr. Wu’s experience in multinational companies brings him strong financial, accounting, and management backgrounds to quickly capture the business needs of his clients and to develop the best possible legal solutions for clients. Mr. Wu’s working experience in both China and the United States has allowed him to engage in immigration matters, particularly in business immigration EB-5, L-1 and H1B, with the best entry point for clients to understand US law and business models; In the field of civil litigation, Mr. Wu adhere to the interests of the customer first, with particular emphasis on customer communication, and actively developing cost-effective litigation strategy.",
  "news_content28": "SAC Attorneys LLP website:",
  "news_content29": "http://www.sacattorneys.com"
},
{
  "id": 3,
  "home_image": "http://usjus.org/wp-content/uploads/2019/11/PDA1107-1024x683.jpg",
  "home_title": "PDA Startup Workshop Event #6",
  "public_time": "November 7, 2019",
  "author": "USJ",
  "news_content": "PDA Startup Workshop Event #6 was successfully hold at the Afternoon of Nov 2,2019"
}
]