module.exports.courses = [
  {
    "id": 1,
    "thumb": "/images/c1.jpg",
    "name": "Deep Learning",
    "uname": "AI Workshop Training Program",
    "sorts": "(A - 25 hours of systematic training)", 
    "sorts1": "(B - 20 hours for prototype project)",
    "sorts2": "(C - practical project development for 20 hours)",
    "title": "Class Title",
    "detail": "Deep Learning Engineer(A) (25 hours + 25 hours)",
    "detail1": "2020AI-A-01",
    "code": "Course Code",
    "detail2": "AI-A-101",
    "lecturer": "Lecturer",
    "detail3": "Andy Tian",
    "module": "Course Module",
    "detail4": "Video Structure Analysis, Object Detection and Tracking, Character Recognition, Action Recognition, Course Contents, and Activity Recognition.",
    "content": "Course Content",
    "detail5": "Dividing the video into frames, super frames, shots, scenes, and stories to deal and express at multiple levels such as vehicle tracking.",
    "detail6": "The safer area identifies the people who appeared in the video; Emotion semantic analysis to identify the actions of the characters in the video; What kind of psychological experience the audience will have when they are watching some certain videos.",
    "aims": "Project Objectives",
    "detail7": "Design and Implementation of a Human/Animal Identification System.",
    "time": "Class Time",
    "detail8": "The daytime, evening and weekend classes. The specific time of the classes depends on the notice."
  },
  {
    "id": 2,
    "thumb": "/images/c2.jpg",
    "name": "Big Data",
    "uname": "Big Data Workshop Training Program",
    "sorts": "(A - 25 hours of systematic training)", 
    "sorts1": "(B - 20 hours for prototype project)",
    "sorts2": "(C - practical project class development for 20 hours)",
    "title": "Class Title",
    "detail": "Big Data Engineer(A) (25 hours + 25 hours)",
    "detail1": "2020 BD-A-01",
    "code": "Course Code",
    "detail2": "BD-A-001",
    "lecturer": "Lecturer",
    "detail3": "Dr. Ted Sun",
    "module": "Course Content",
    "detail4": ["1) Hadoop + MPP RDB / SMP RDB; Architecture mode", " 2) The processing method based on Hadoop deal with unstructured Data (Auxiliary) and RDB deal with structured data (Main)", " 3) Hadoop unstructured solutions",
     " 4) MPP RDB / SMP PDB + Hadoop structure or distributed file system solutions", " 5) Case development in Silicon Valley."],
     "content": "Teaching language",
     "detail5": "English (Available for translation)",
     "detail6": "Chinese",
     "aims": "Practical Case",
     "detail7": "BD Health Care, Intelligence Comparison Price",
     "time": "Class Time",
     "detail8": "The daytime, evening and weekend classes. The specific time of the classes depends on the notice."
  },
  {
    "id": 3,
    "thumb": "/images/c3.jpg",
    "name": "Block Chain",
    "uname": "Blockchain Workshop Training Program",
    "sorts": "(A - 25 hours of systematic training)", 
    "sorts1": "(B - 20 hours for prototype project)",
    "sorts2": "(C - practical case development for 20 hours)",
    "title": "Class Title",
    "detail": "Blockchain Engineer(A) (80 hours + practical program of 80 hours)",
    "detail1": "2020 BC-A-01",
    "code": "Course Code",
    "detail2": "BC-A-301",
    "lecturer": "Lecturer",
    "detail3": "Mr. Fei Zou",
    "module": "Course Content",
    "detail4": ["1) Introduction to Blockchain", " 2) Client installation and Operation", " 3) Bit Coins and Ether Coins network",
    " 4) E-Wallet", " 5) Smart Contract Programming", " 6) Solitidy complex variable types, methods, inheritance, Events, and programming", 
    " 7) Decentralized application of Dapp."],
    "content": "Practical Case",
    "detail5": "E-wallet Contract Project",
    "detail6": "Smart Contract Project",
    "aims": "Project Objectives",
    "detail7": "Have a strong dissection of the E-wallet/Smart Contract Project, and understand the operation mode and marketization rules of the blockchain.",
    "time": "Class Time",
    "detail8": "The daytime, evening and weekend classes. The specific time of the classes depends on the notice."
  },
  {
    "id": 4,
    "thumb": "/images/c4.jpg",
    "name": "Self Marketing",
    "uname": "Blockchain Workshop Training Program",
    "sorts": "(A - 25 hours of systematic training)", 
    "sorts1": "(B - 20 hours for prototype project)",
    "sorts2": "(C - practical case development for 20 hours)",
    "title": "Class Title",
    "detail": "Self-marketing Management (A)",
    "detail1": "2020 SMM-A-01",
    "code": "Course Code",
    "detail2": "SMM-A-401",
    "lecturer": "Lecturer",
    "detail3": "Dr. Yun Wang",
    "module": "Course Content",
    "detail4": ["1) The self-marketing business plan management", " 2) Empathize with customers", " 3) How to conduct customer with experience",
    " 4) Service rollover implementation", " 5) Value-added sharing scheme", " 6) Self-marketing evaluation and improvement", 
    " 7) Self-evaluation of marketing effect", " 8) Marketing anchor plan."],
    "content": "Practical Case",
    "detail5": "The case of the marketing management",
    "aims": "Project Objectives",
    "detail7": "The embodiment and application of the complete self-marketing theoretical system in real life.",
    "time": "Class Time",
    "detail8": "The daytime, evening and weekend classes. The specific time of the classes depends on the notice."
  }
]

module.exports.cdetails = [
  {
    "id": 1,
    "thumb": "/images/c1.jpg",
    "name": "Deep Learning",
  },
  {

  }
]